[package]
name = "critic-rs"
version = "0.1.0"
authors = ["Christopher Davison <c.jr.davison@gmail.com>"]

[dependencies]
argparse = "*"

[lib]
name = "critic"
path = "src/lib.rs"

[[bin]]
name = "critic"
path = "src/main.rs"
